tap "ddev/ddev"
tap "homebrew/bundle"
tap "homebrew/services"
tap "platformsh/tap"
brew "glib"
brew "cairo"
brew "curl"
brew "composer"
brew "dnsmasq"
brew "docker", link: false
brew "gh"
brew "gpatch"
brew "harfbuzz"
brew "httpd"
brew "jq"
brew "mailhog"
brew "nghttp2"
brew "nginx"
brew "node"
brew "node-build"
brew "nodenv"
brew "openjdk"
brew "pv"
brew "pyenv"
brew "ruby-build"
brew "rbenv"
brew "rbenv-bundler"
brew "redis"
brew "solr", link: false
brew "solr@8.11", restart_service: true
brew "tcl-tk"
brew "wget"
brew "yarn"
brew "ddev/ddev/ddev"
brew "platformsh/tap/platformsh-cli"
cask "docker"
