tap "ddev/ddev"
tap "homebrew/bundle"
tap "homebrew/services"
tap "platformsh/tap"
brew "curl"
brew "composer"
brew "docker", link: false
brew "gpatch"
brew "jq"
brew "nghttp2"
brew "nginx"
brew "pv"
brew "wget"
brew "yarn"
brew "ddev/ddev/ddev"
brew "platformsh/tap/platformsh-cli"
cask "docker"
